const NEWS = [
    "AI content has been on the rise. Those classic incrementals seems to be declining in quantity.",
    "Classicslop",
    "Slop Slop Slop",
    "Are nodebusters really that bad? (Questions everyone)",
    "Check out this new game called Danny Clicker! It's a clicker, but with Danny!",
    "Check out this new game called 67 Clicker! So funny!",
    "Are clickers incrementals?",
    "Are incrementals clickers?",
    "Are idle games incrementals?",
    "Are incrementals idle games?",
    "Antimatter has been on the rise for slop. Slopimatter is then created.",
    "Antimatter has annhilated all the AI slop for free! Thanks!",
    "AI and Antimatter has some sort of vowel alliteration, which I forgot what that was called",
    "1+1 = 2, a fact",
    "Check out Phigros, the best free rhythm game",
    "Superspruce please come back...",
    "Inspired by Katakana's Infinite Layers, common trends, antimatter, and null matter!",
    "Inspired by nobody, that's what I'd have said if this was made in 2021",
    "The golden age has fallen",
    "More news... <span onclick='window.alert(`You got a paperclip!`)'>Click here for free paperclips!</span>",
    "News Tickers in the big 26...",
    "CaCO3",
    "Welcome to Phigros- Oops Wrong game",
    "Welcome to maimai- shit",
    "Welcome to CHUNITHM, wait I think this is the wrong game",
    "Welcome to Antimatter Dimensions! In here you get antimatter, don't be fooled! Those points ARE antimatter",
    "What even are points? What are they for? (Deep thinking; 150s)",
    "Points vs Coins vs Antimatter, the fight never ends",
    "News tickers at its best state, 1000 unique news messages...",
    "Currently, there are 67 news messages, I mean there isn't, probably more or less",
    "Universe shrinker is a good game.",
    "Inspiration from everyone that existed.",
    "We might have to go to the church for this one",
    "MIKUMIKUMIKU",
    "TETOTETOTETO",
    "You should've listened to vocaloid without noticing, nyan cat is a vocaloid (surprising, right?)",
    "RNGDelak did NOT contribute on this.",
    "W3Schools did NOT contribute on this.",
    "No AI was used in the entirety of the project. Even if it was used, who tf could've balanced this log slop",
    "Jarvis, more logrithms!",
    "Jarvis, more electricty!",
    "Jarvis, more Jarvises! Wait wasn't this how replicantii works OH NOOOOO",
    "Jarvis, ... Where are you",
    "Jarvis, welcome to the end of the world. You need to restore the world. Replicate.",
    "LRLRUUDDBA",
    "This message was NOT transmitted via Morse Code",
    "Nigerian Ball Association, or the NBA",
    "There is at least one developer doing 67 incremental as a joke but making it a real game",
    "Every joke can be expanded into a real idea. I said it.",
    "Go for it!",
    "If you are struggling to prestige, why not buy upgrades?",
    "If you're struggling to buy upgrades, why not prestige?",
    "You have a chance of viewing this news ticker. I guess this is a news ticker why wouldn't there be a chance?",
    "69 vs 67. Only the wise knows it.",
    "Infinite Layers might be a good game, but how about Eternal Layers? &omega;<sup>2</sup> layers would surely be good",
    "How much prestige layers does life have? 1. That's your birth, and death. One run plays 70 years and beyond.",
    "Life is valuable, because when you die you can't play incrementals.",
    "How to unbalance your game? Mmmmmm",
    "How to ANTIMATTER balance your game? This.",
    "This game serves as an example on how NOT to make an incremental",
    "Roblox",
    "Minecraft",
    "Fortnite",
    "Tung Tung Tung Sahur",
    "[Insert AI slop message]",
    "Hello! How may I assist you?",
    "This is LarpGPT",
    "GPT means useless, as of today.",
    "Claude Fable 1.798e308",
    "GPT (1.79e308 Archverses) Ultra 1.79e308",
    "Claude Fable+ e1.79e308",
    "Qwen 1.79e308",
    "Deepseek V1.79e308-1.79e308",
    "[Insert swear word]",
    "(0,0,0)(1,1,1)(2,1,0)(1,1,1)",
    "&psi(M<sub>&omega;+1</sub>)",
    "78 means something bad you DO not want to search it",
    "Ass",
    "CheatGPT",
    "This game was made under the assistance of IA. What is IA? Intelluctal artifacts, a currency that does NOT exist",
    "I like emphasizing all the is's and isn't's",
    "Have you read transition to proof",
    "I think there are a few great Math books.",
    "Mathematics in the AI rat race be like: Me be like: He: She:",
    "Trans rights",
    "Bisexual rights",
    "Crystal rights",
    "Support Gay rights!",
    "I don't support Gay rights.",
    "I don't support AI being used in incrementals. Because the game that companies are playing right now is already an incremental.",
    "Read this out aloud",
    "\\",
    "Gunmu message",
    "100 rows of agony: The Tree",
    "Please join &omega;-Y LNGI",
    "LNGIs are the best genre of videos ever, they give so much dopamine",
    "Life is so useless.",
    "What happens after death? We don't know and we will never know. That's what makes life valuable. --Me",
    "67",
    "6767",
    "676767"
]

function update_news() {
    document.getElementById("news_ticker").innerHTML = NEWS[Math.floor(Math.random()*NEWS.length)]
}

update_news()
setInterval(update_news,6000,1)