const NEWS = [
    "AI content has been on the rise. Those classic incrementals seems to be declining in quantity.",
    "Classicslop",
    "Slop Slop Slop",
    "Are nodebusters really that bad? (Questions everyone)",
    "Check out this new game called Danny Clicker! It's a clicker, but with Danny!",
    "Check out this new game called 67 Clicker! So funny!",
    "Are clickers incrementals?",
    "Are incrementals clickers?",
    "Are idle games incrementals?",
    "Are incrementals idle games?",
    "Antimatter has been on the rise for slop. Slopimatter is then created.",
    "Antimatter has annhilated all the AI slop for free! Thanks!",
    "AI and Antimatter has some sort of vowel alliteration, which I forgot what that was called",
    "1+1 = 2, a fact",
    "Check out Phigros, the best free rhythm game",
    "Superspruce please come back...",
    "Inspired by Katakana's Infinite Layers, common trends, antimatter, and null matter!",
    "Inspired by nobody, that's what I'd have said if this was made in 2021",
    "The golden age has fallen",
    "More news... <span onclick='window.alert(`You got a paperclip!`)'>Click here for free paperclips!</span>",
    "News Tickers in the big 26...",
    "CaCO3",
    "Welcome to Phigros- Oops Wrong game",
    "Welcome to maimai- shit",
    "Welcome to CHUNITHM, wait I think this is the wrong game",
    "Welcome to Antimatter Dimensions! In here you get antimatter, don't be fooled! Those points ARE antimatter",
    "What even are points? What are they for? (Deep thinking; 150s)",
    "Points vs Coins vs Antimatter, the fight never ends",
    "News tickers at its best state, 1000 unique news messages...",
    "Currently, there are 67 news messages, I mean there isn't, probably more or less",
    "Universe shrinker is a good game.",
    "Inspiration from everyone that existed.",
    "We might have to go to the church for this one",
    "MIKUMIKUMIKU",
    "TETOTETOTETO",
    "You should've listened to vocaloid without noticing, nyan cat is a vocaloid (surprising, right?)",
    "RNGDelak did NOT contribute on this.",
    "W3Schools did NOT contribute on this.",
    "No AI was used in the entirety of the project. Even if it was used, who tf could've balanced this log slop",
    "Jarvis, more logrithms!",
    "Jarvis, more electricty!",
    "Jarvis, more Jarvises! Wait wasn't this how replicantii works OH NOOOOO",
    "Jarvis, ... Where are you",
    "Jarvis, welcome to the end of the world. You need to restore the world. Replicate.",
    "LRLRUUDDBA",
    "This message was NOT transmitted via Morse Code",
    "Nigerian Ball Association, or the NBA",
    "There is at least one developer doing 67 incremental as a joke but making it a real game",
    "Every joke can be expanded into a real idea. I said it.",
    "Go for it!",
    "If you are struggling to prestige, why not buy upgrades?",
    "If you're struggling to buy upgrades, why not prestige?",
    "You have a chance of viewing this news ticker. I guess this is a news ticker why wouldn't there be a chance?",
    "69 vs 67. Only the wise knows it.",
    "Infinite Layers might be a good game, but how about Eternal Layers? &omega;<sup>2</sup> layers would surely be good",
    "How much prestige layers does life have? 1. That's your birth, and death. One run plays 70 years and beyond.",
    "Life is valuable, because when you die you can't play incrementals."
]

function update_news() {
    document.getElementById("news_ticker").innerHTML = NEWS[Math.floor(Math.random()*NEWS.length)]
}

update_news()
setInterval(update_news,6000,1)